# Generated by Django 2.2.17 on 2020-11-25 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20201125_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='house_rules',
            new_name='houserules',
        ),
    ]
